name: "${project.name}"
version: ${version}
main: ${mainClass}

load: ${bukkitPlugin.load}
database: ${bukkitPlugin.database}

depend: [${bukkitPlugin.depend}]
softdepend: [${bukkitPlugin.softdepend}]
loadbefore: [${bukkitPlugin.loadbefore}]

description: "${project.description}"
author: '${project.developers[0].id}'
authors: [${project.developers[1].id}]
website: "${project.url}"

commands:
  sidconfre:
    description: 'Reloads the Special Item-Drop configuration file and updates the listener.'
    usage: /<command>
    permission: sid.reload
    aliases: [sid, specialitemdrops, sidconfigreload, sidreload, sidconf, sidre]
